### ISSUE TITLE
beautify the page

### ISSUE THREAD

**Issue by piyush-kurur** [indian-curry/indian-curry.github.io#3]
the website is currently quite baroque. Might be good to add some styling say bootstrap+some background

**Comment by piyush-kurur** [comment]
to start with some background from http://subtlepatterns.com/

**Comment by piyush-kurur** [comment]
what do you want to use for css? Easy option `twitter-bootstrap`. I have used it. I donot like but 
one does not need to tweak too much to get things like mobile response etc. On my homepage I have some custom style that I built out of compass but I donot want to spend that much time again (forgot compass). @ajnsit @psibi @saurabhnanda  does any of you have some strong opinion?

**Comment by psibi** [comment]
No strong opinions, but using twitter bootstrap will save us a lot of effort. :)

**Comment by ajnsit** [comment]
I'm personally fine with the current site as is. It's functional, and not overly ugly :) Though twitter bootstrap is never the wrong choice either if someone can find a bit of time to integrate that into the code.

**Comment by piyush-kurur** [comment]
Okey I am going with a basic bootstrap based layout. Please feel free to send me asthetically more pleasing stuff.

**Comment by piyush-kurur** [comment]
I am happy now with the current looks. Any one want to have a go at it please feel free. More importantly we should work towards the announcement. Closing this now.
