### ISSUE TITLE
Mailing list

### ISSUE THREAD

**Issue by piyush-kurur** [indian-curry/indian-curry.github.io#5]
Setting up of a mailing list (google groups).

**Comment by piyush-kurur** [comment]
@saurabhnanda  can you set this up in google groups and let me know

**Comment by saurabhnanda** [comment]
Created the group. Invited ppk@cse.iitk.ac.in to be a member. Will add you
as an owner once you accept.

**Comment by piyush-kurur** [comment]
On Wed, Sep 07, 2016 at 05:45:53AM -0700, Saurabh Nanda wrote:

> Created the group. Invited ppk@cse.iitk.ac.in to be a member. Will add you
> as an owner once you accept.

Accepted. Just a question. To keep the naming consistent maybe indian-curry
is better.

**Comment by piyush-kurur** [comment]
If possible rename the list to indian-curry@googlegroups

**Comment by saurabhnanda** [comment]
Strangely, indian-curry@googlegroups.com seems to be taken, but I can't
find it anywhere on google groups. It could be that they're trying to
prevent "squatting", but the only way to find that out is by first deleting
indiancurry@ and recreating.

**Comment by saurabhnanda** [comment]
Messages to indian-curry@googlegroups.com are bouncing with a boilerplate message in **french**:

> Bonjour saurabh@vacationlabs.com,
> 
> Il se peut que le groupe que vous avez essayé de contacter (indian-curry) n'existe pas ou que vous ne soyez pas autorisé à lui envoyer des messages. Voici quelques-unes des raisons possibles pour lesquelles votre message n'a pas pu être envoyé :
> - Vous avez mal orthographié le nom du groupe.
> - Le propriétaire du groupe l'a peut-être supprimé.
> - Vous devez être abonné avant de pouvoir envoyer des messages.
> - Ce groupe n'autorise pas l'envoi de message.
> 
> Si vous avez des questions sur ce groupe ou tout autre groupe Google, consultez le centre d'aide à l'adresse https://groups.google.com/support/.
> 
> Merci,
> 
> Google Groups

**Translation:**

> Hello saurabh@vacationlabs.com ,
> 
> It may be that the group you tried to contact ( indian- curry ) does not exist or you are not allowed to send messages . Here are some possible reasons why your message could not be sent :
> - You misspelled the name of the group.
> - The owner of the group may be removed.
> - You must subscribe before you can post messages.
> - This group does not allow sending message.
> 
> If you have questions about this or any other Google group , please visit the Help Center at https://groups.google.com/support/ .
> 
> thank you,
> 
> Google Groups

**Comment by piyush-kurur** [comment]
On Fri, Sep 09, 2016 at 12:19:48AM -0700, Saurabh Nanda wrote:

> Strangely, indian-curry@googlegroups.com seems to be taken, but I can't
> find it anywhere on google groups. It could be that they're trying to
> prevent "squatting", but the only way to find that out is by first deleting
> indiancurry@ and recreating.

Since we do not have any other members it is okey if you delete it. I would however
see if there is a customer support email and tell them our requirement.

Regards,

ppk

**Comment by piyush-kurur** [comment]
On Fri, Sep 09, 2016 at 12:19:48AM -0700, Saurabh Nanda wrote:

> Strangely, indian-curry@googlegroups.com seems to be taken, but I can't
> find it anywhere on google groups. It could be that they're trying to
> prevent "squatting", but the only way to find that out is by first deleting
> indiancurry@ and recreating.

There should be a way to rename instead of create a fresh. That would avoid the squatting
problem I guess

**Comment by piyush-kurur** [comment]
what is the status of this? can you check and report back?

**Comment by piyush-kurur** [comment]
I think it is fine to just stick to indiancurry (i.e. without the hypen) if things are not working out.

**Comment by saurabhnanda** [comment]
let me take a last try on this and close. was busy with other stuff over
the past week.

**Comment by saurabhnanda** [comment]
shucks -- we seem to be in a worse situation now. I deleted indiancurry@
and now it's not allowing me to re-create either india-curry@ or
indiancurry@

**Comment by piyush-kurur** [comment]
On Thu, Sep 29, 2016 at 10:27:17PM -0700, Saurabh Nanda wrote:

> shucks -- we seem to be in a worse situation now. I deleted indiancurry@
> and now it's not allowing me to re-create either india-curry@ or
> indiancurry@

This is yucks. Is there any way we can contact their support system ?

Regards,

ppk

**Comment by saurabhnanda** [comment]
Google is notorious for not giving support for paid products, how can we
expect anything for a free service. btw, indian_curry@ is available.
Alternatively, we can host the mailing list on some other platform (not
Google Groups). Any recommendations?

**Comment by saurabhnanda** [comment]
Got indiancurry@ back -- I guess there's a timeout in their system before
the name can be reused. Let's just stick with this and move on. Unless
indian_curry@ is preferable?

**Comment by piyush-kurur** [comment]
On Fri, Sep 30, 2016 at 12:58:40AM -0700, Saurabh Nanda wrote:

> Got indiancurry@ back -- I guess there's a timeout in their system before
> the name can be reused. Let's just stick with this and move on. Unless
> indian_curry@ is preferable?

Let us stick to indiancurry  and be done with it.

Regards,

ppk

**Comment by piyush-kurur** [comment]
If every thing is working can you updated the announcement post and close this ticket.

**Comment by piyush-kurur** [comment]
The list is working I have already sent a mail. I am closing this ticket.

So we are finalising on the list name indiancurry@googlegroups.com (without a hyphen)
